### ISSUE TITLE
Hyper parameter optimization epoch parameter 

### ISSUE THREAD

**Issue by FoppeCrezee** [arturomoncadatorres/deepsurvk#110]
#### Describe the current situation
In the function optimize_hp from the optimization.py file a set of parameters is optimized over a set of 1000 epochs. However, the amount of epochs is highly dependable on the data and parameter set we are optimizing. So sometimes you would run, to save on runtime and sometimes you would want to run more. 

#### Describe your proposed feature/improvement
The feature I propose is the implementation of an additional parameter in the optimize_hp() function. This parameter would let you set the amount of epochs manually, but could be set to 1000 as a default.

**Comment by arturomoncadatorres** [comment]
It makes sense giving the user the option to define the number of epochs. After all, this greatly depends on the data at hand.

I added this functionality in the `optimize_hp` function. The prototype remains the same, but the number of epochs `epochs` can now be passed as an additional entry to the `params` dictionary with key `epochs` and value a list comprised of only one element. If the list has more than one element, only the first one will be considered. If the number of epochs isn't defined by the user, then a default of 1000 will be used.

This was done in commits 528809b9dfc2771b35bc76431a33e0081463ad04 and 8deb560e8f3db3be776480932a1bc04b779f0247
