### ISSUE TITLE
brier_score AND integrated_brier_score

### ISSUE THREAD

**Issue by CKA-JAY** [arturomoncadatorres/deepsurvk#205]
May I ask how I can calculate the values of brier_score and integrated_brier_score using the deepsurvey algorithm. I also searched for some methods online, but they were not successful. So I request your help and ideas. Thank you

**Comment by arturomoncadatorres** [comment]
Unfortunately, DeepSurvK doesn't support that functionality. However, I suggest you take a look at [`scikit-survival`](https://scikit-survival.readthedocs.io/en/stable/index.html), which has both functions to calculate the [Brier score](https://scikit-survival.readthedocs.io/en/stable/api/generated/sksurv.metrics.brier_score.html) (for right-censored data) and the [integrated Brier score](https://scikit-survival.readthedocs.io/en/stable/api/generated/sksurv.metrics.integrated_brier_score.html#sksurv.metrics.integrated_brier_score).
